# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b980962c2ee408464157148a0e36ae6377309c746bedfeb654c2a397fd2b0f5fc4a44748c82f5751242b8509ff381ce85d2058e6743e3b949eb1c6d8a3f06a45

test:
  secret_key_base: 379709aca60b5987b410837556223e942fbfb9cd847079c19160ae45dee5aa8e1f766da5c504b524277f7b1b6dff01f7e36de372bb70f2d8eae29d054e6c0193

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
